//Name: Samuel Olagoke
# --Date: October 17, 2025
# --Course: IT202-003
# --Assignment: Phase02
# --Email: sio6@njit.edu

POST http://localhost:3000/addshirt.test.php
Content-Type: application/x-www-form-urlencoded

ShirtID=6000
&ShirtCode=LCN
&ShirtName=Latest Crew Neck
&ShirtDescription=A shirt with a crew neck design
&ShirtSeason=Summer
&ShirtSize=Medium
&ShirtTypeID=200
&ShirtWholesalePrice=15.00
&ShirtListPrice=29.99
###
GET http://localhost:3000/listshirt.test.php
###
POST http://localhost:3000/changeshirt.test.php
Content-Type: application/x-www-form-urlencoded

ShirtID=6000
&ShirtCode=NCN
&ShirtName=New Crew Neck
&ShirtDescription=A shirt with a newer crew neck design
&ShirtSeason=Spring
&ShirtSize=Medium
&ShirtTypeID=200
&ShirtWholesalePrice=18.00
&ShirtListPrice=39.99
###
POST http://localhost:3000/removeshirt.test.php
Content-Type: application/x-www-form-urlencoded

ShirtID=6000


