//Name: Samuel Olagoke
# --Date: October 17, 2025
# --Course: IT202-003
# --Assignment: Phase02
# --Email: sio6@njit.edu

POST http://localhost:3000/addshirttype.test.php
Content-Type: application/x-www-form-urlencoded

ShirtTypeID=600
&ShirtTypeCode=STS
&ShirtTypeName=Sweater Shirt
&ShirtAisle=4
###
GET http://localhost:3000/listshirttypes.test.php
###
POST http://localhost:3000/changeshirttype.test.php
Content-Type: application/x-www-form-urlencoded

ShirtTypeID=600
&ShirtTypeCode=POLE
&ShirtTypeName=Polyester
&ShirtAisle=2
###
POST http://localhost:3000/removeshirttype.test.php
Content-Type: application/x-www-form-urlencoded

ShirtTypeID=600